In [10]:
# Import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
from scipy import stats
import statsmodels.api as sm
import warnings
from itertools import product
from datetime import datetime
import pyspark.sql.functions as F
warnings.filterwarnings('ignore')
plt.style.use('seaborn-poster')

ModuleNotFoundError: No module named 'pyspark'

In [2]:
philippine_df = pd.read_csv("https://raw.githubusercontent.com/zalven/covid-19-prediction-2021/main/covid_prediction_data/philippines_covid_cases.csv")

In [3]:
philippine_df.tail()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality
494,PHL,Asia,Philippines,2021-06-07,1276004.0,6526.0,6529.000,21969.0,71.0,143.286,...,NaN,370.437,7.07,7.8,40.8,78.463,1.0,71.23,0.718,NaN
495,PHL,Asia,Philippines,2021-06-08,1280773.0,4769.0,6472.286,22064.0,95.0,150.286,...,NaN,370.437,7.07,7.8,40.8,78.463,1.0,71.23,0.718,NaN
496,PHL,Asia,Philippines,2021-06-09,1286217.0,5444.0,6500.143,22190.0,126.0,147.429,...,NaN,370.437,7.07,7.8,40.8,78.463,1.0,71.23,0.718,NaN
497,PHL,Asia,Philippines,2021-06-10,1293687.0,7470.0,6541.143,22312.0,122.0,136.429,...,NaN,370.437,7.07,7.8,40.8,78.463,1.0,71.23,0.718,NaN
498,PHL,Asia,Philippines,2021-06-11,1300349.0,6662.0,6430.286,22507.0,195.0,138.571,...,NaN,370.437,7.07,7.8,40.8,78.463,1.0,71.23,0.718,NaN

In [13]:

# Resampling to monthly frequency
df_month = philippine_df.resample('M').mean()

# Resampling to annual frequency
df_year = philippine_df.resample('A-DEC').mean()

# Resampling to quarterly frequency
df_Q = philippine_df.resample('Q-DEC').mean()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'